enum class EUnitRole {
    Husband = 0,
    Wife = 1,
    Son = 2,
    Daughter = 3,
    Retainer = 4,
    Soldier = 5,
    FreeMerchant = 6,
    FreeLivestockMerchant = 7,
    Deer = 8,
    Chicken = 9,
    Sheep = 10,
    Lamb = 11,
    Ox = 12,
    Goat = 13,
    Hound = 14,
    Horse = 15,
    Mule = 16,
    BanditRecruit = 17,
    EUnitRole_MAX = 18,
};
